import type { Plot } from './types';

export const SAMPLE_PLOTS: Plot[] = [
  {
    id: 'p-0142-2a',
    villageId: 'v-gangapur',
    village: { name: 'Gangapur', nameMr: 'गंगापूर', taluka: 'Nashik', district: 'Nashik' },
    gatNumber: '142/2-A',
    surveyNumber: '58',
    ctsNumber: null,
    reraNumber: 'P51600012345',
    areaSqm: 223,
    areaSqft: 2400,
    frontRoadMeters: 9,
    landType: 'NA',
    dpZone: 'green',
    reservation: null,
    fsiAllowed: 1.1,
    tdrAllowed: 0.3,
    readyReckonerRate: 19200 / 10.7639, // ₹/sqm derived
    askMarketRate: 24200 / 10.7639,
    lastTxnRate: 22800 / 10.7639,
    deltaPct: 35,
    verified: true,
    listedAt: '2026-04-10T09:00:00+05:30',
    source: 'owner',
    slug: 'gangapur-gat-142-2a',
  },
  {
    id: 'p-0077-1',
    villageId: 'v-shirwade',
    village: { name: 'Shirwade', nameMr: 'शिरवाडे', taluka: 'Igatpuri', district: 'Nashik' },
    gatNumber: '77/1',
    surveyNumber: null,
    ctsNumber: null,
    reraNumber: null,
    areaSqm: 4047,
    areaSqft: 43560,
    frontRoadMeters: 6,
    landType: 'AGRI_NA_POTENTIAL',
    dpZone: 'yellow',
    reservation: null,
    fsiAllowed: 0.3,
    tdrAllowed: 0,
    readyReckonerRate: 350,
    askMarketRate: 556,
    deltaPct: 58,
    verified: true,
    listedAt: '2026-04-14T12:10:00+05:30',
    source: 'agent',
    slug: 'shirwade-gat-77-1',
  },
  {
    id: 'p-0214-cts9812',
    villageId: 'v-makhmalabad',
    village: { name: 'Makhmalabad', nameMr: 'मखमलाबाद', taluka: 'Nashik', district: 'Nashik' },
    gatNumber: null,
    surveyNumber: '214',
    ctsNumber: '9812',
    reraNumber: null,
    areaSqm: 539,
    areaSqft: 5800,
    frontRoadMeters: 12,
    landType: 'RESERVED',
    dpZone: 'red',
    reservation: 'school',
    fsiAllowed: 0,
    tdrAllowed: 0,
    readyReckonerRate: 20000,
    askMarketRate: undefined,
    deltaPct: 0,
    verified: true,
    listedAt: '2026-04-09T10:20:00+05:30',
    source: 'builder',
    slug: 'makhmalabad-svy-214-cts-9812',
  },
];
